apiVersion: v1
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: kubenametester
    spec:
      selector:
        matchLabels:
          app: kubenametester
      replicas: 1
      template:
        metadata:
          labels:
            app: kubenametester
        spec:
          containers:
            - name: kubenametester
              image: "barisv/kubenametester:latest"
              imagePullPolicy: Always
          terminationGracePeriodSeconds: 30
kind: List
metadata: {}
